/**
 * RegistrationView - DB登録確認画面 (SCR-004)
 * INSERTデータ確認・登録
 */
import { useState, useCallback, useEffect } from 'preact/hooks';
import { useAppDispatch, useAppSelector } from '../../redux/store';
import {
  registerFile,
  clearRegistrationResult,
  clearAnalysisResult,
  fetchAnalysisResult,
  clearError
} from '../../redux/slices/denpyoSlice';
import { useLocation, useNavigate } from 'react-router-dom';
import { APP_ROUTES } from '../../constants/routes';
import { t } from '../../i18n';
import type { AnalysisResult, ExtractedField, RegistrationRequest } from '../../types/denpyoTypes';
import {
  ArrowLeft,
  Database,
  FileText,
  Table2,
  Sparkles,
  Loader2,
  CheckCircle2,
  AlertCircle,
  Plus,
  Trash2
} from 'lucide-react';
import { DocumentPreviewWorkspace } from '../../components/DocumentPreviewWorkspace';

const AUTO_GENERATED_HEADER_COLUMNS = new Set(['HEADER_ID']);
const AUTO_GENERATED_LINE_COLUMNS = ['HEADER_ID', 'LINE_ID'];

function normalizeColumnName(value: string | null | undefined): string {
  return String(value ?? '').trim().toUpperCase();
}

function isAutoGeneratedHeaderField(field: ExtractedField): boolean {
  return AUTO_GENERATED_HEADER_COLUMNS.has(normalizeColumnName(field.field_name_en || field.field_name));
}

function isAutoGeneratedLineColumn(columnName: string): boolean {
  return AUTO_GENERATED_LINE_COLUMNS.includes(normalizeColumnName(columnName));
}

function collectLineColumns(analysisResult: AnalysisResult, lineRows: Record<string, string>[]): string[] {
  const orderedColumns: string[] = [];
  const seenColumns = new Set<string>();

  const pushColumn = (columnName: string | null | undefined) => {
    const label = String(columnName ?? '').trim();
    if (!label) return;

    const normalizedName = normalizeColumnName(label);
    if (seenColumns.has(normalizedName)) return;

    seenColumns.add(normalizedName);
    orderedColumns.push(label);
  };

  analysisResult.table_schema?.line_columns?.forEach(column => pushColumn(column.column_name));
  analysisResult.extraction.line_fields?.forEach(field => pushColumn(field.field_name_en || field.field_name));
  lineRows.forEach(row => Object.keys(row || {}).forEach(pushColumn));

  const regularColumns: string[] = [];
  const systemColumns: string[] = [];
  orderedColumns.forEach(column => {
    if (isAutoGeneratedLineColumn(column)) {
      systemColumns.push(column);
      return;
    }
    regularColumns.push(column);
  });

  systemColumns.sort((a, b) => {
    return AUTO_GENERATED_LINE_COLUMNS.indexOf(normalizeColumnName(a)) - AUTO_GENERATED_LINE_COLUMNS.indexOf(normalizeColumnName(b));
  });

  return [...regularColumns, ...systemColumns];
}

function createEmptyLineRow(columns: string[]): Record<string, string> {
  const row: Record<string, string> = {};
  columns.forEach(column => {
    row[column] = '';
  });
  return row;
}

export function RegistrationView() {
  const dispatch = useAppDispatch();
  const analysisResult = useAppSelector(state => state.denpyo.analysisResult);
  const isRegistering = useAppSelector(state => state.denpyo.isRegistering);
  const registrationResult = useAppSelector(state => state.denpyo.registrationResult);
  const isAnalyzing = useAppSelector(state => state.denpyo.isAnalyzing);
  const error = useAppSelector(state => state.denpyo.error);
  const navigate = useNavigate();
  const location = useLocation();
  const fileId = new URLSearchParams(location.search).get('fileId');
  const currentAnalysisResult = analysisResult && (!fileId || String(analysisResult.file_id) === String(fileId))
    ? analysisResult
    : null;

  const [headerTableName, setHeaderTableName] = useState('');
  const [lineTableName, setLineTableName] = useState('');
  const [headerFields, setHeaderFields] = useState<ExtractedField[]>([]);
  const [lineRows, setLineRows] = useState<Record<string, string>[]>([]);
  const [isConfirmed, setIsConfirmed] = useState(false);
  const [validationError, setValidationError] = useState('');
  const [activeTab, setActiveTab] = useState<'header' | 'line'>('header');

  useEffect(() => {
    dispatch(clearRegistrationResult());
    dispatch(clearError());
  }, [dispatch, fileId]);

  useEffect(() => {
    if (!fileId || currentAnalysisResult) return;
    dispatch(fetchAnalysisResult(fileId));
  }, [currentAnalysisResult, dispatch, fileId]);

  useEffect(() => {
    if (!currentAnalysisResult) return;

    const ddl = currentAnalysisResult.ddl_suggestion;
    setHeaderTableName(ddl.header_table_name || '');
    setLineTableName(ddl.line_table_name || '');
    setHeaderFields(currentAnalysisResult.extraction.header_fields || []);

    const extractedLines = (currentAnalysisResult.extraction.raw_lines || []).map(row => {
      const normalized: Record<string, string> = {};
      Object.entries(row || {}).forEach(([key, value]) => {
        normalized[key] = String(value ?? '');
      });
      return normalized;
    });

    if (extractedLines.length > 0) {
      setLineRows(extractedLines);
    } else {
      const fallbackLine: Record<string, string> = {};
      (currentAnalysisResult.extraction.line_fields || []).forEach(field => {
        const key = field.field_name_en || field.field_name;
        if (key) fallbackLine[key] = String(field.value ?? '');
      });
      setLineRows(Object.keys(fallbackLine).length > 0 ? [fallbackLine] : []);
    }

    setActiveTab('header');
    setIsConfirmed(false);
    setValidationError('');
  }, [currentAnalysisResult]);

  const handleBackToList = useCallback(() => {
    dispatch(clearRegistrationResult());
    dispatch(clearAnalysisResult());
    dispatch(clearError());
    navigate(APP_ROUTES.fileList);
  }, [dispatch, navigate]);

  const updateHeaderFieldValue = (index: number, value: string) => {
    setHeaderFields(prev => prev.map((f, idx) => (idx === index ? { ...f, value } : f)));
  };

  const updateLineCell = (rowIndex: number, col: string, value: string) => {
    setLineRows(prev => prev.map((row, idx) => (idx === rowIndex ? { ...row, [col]: value } : row)));
  };

  const handleRegister = useCallback(async () => {
    if (!currentAnalysisResult) return;

    if (!isConfirmed) {
      setValidationError(t('registration.error.notConfirmed'));
      return;
    }
    if (!headerTableName.trim()) {
      setValidationError(t('registration.error.noHeaderTable'));
      return;
    }
    setValidationError('');

    const normalizedLineRows = lineRows
      .map(row => {
        const normalized: Record<string, string> = {};
        Object.entries(row).forEach(([key, value]) => {
          if (isAutoGeneratedLineColumn(key)) return;

          const textValue = String(value ?? '');
          if (!textValue.trim()) return;

          normalized[key] = textValue;
        });
        return normalized;
      })
      .filter(row => Object.keys(row).length > 0);

    const data: RegistrationRequest = {
      category_id: currentAnalysisResult.category_id,
      category_name: currentAnalysisResult.classification.category,
      category_name_en: currentAnalysisResult.ddl_suggestion.table_prefix || '',
      header_table_name: headerTableName.trim(),
      line_table_name: lineTableName.trim(),
      header_ddl: currentAnalysisResult.ddl_suggestion.header_ddl || '',
      line_ddl: currentAnalysisResult.ddl_suggestion.line_ddl || '',
      ai_confidence: currentAnalysisResult.classification.confidence,
      line_count: normalizedLineRows.length,
      header_fields: headerFields,
      raw_lines: normalizedLineRows,
    };

    dispatch(registerFile({ fileId: currentAnalysisResult.file_id, data }));
  }, [dispatch, currentAnalysisResult, headerTableName, lineTableName, headerFields, lineRows, isConfirmed]);

  if (fileId && !currentAnalysisResult) {
    if (isAnalyzing || !error) {
      return (
        <div class="ics-dashboard ics-dashboard--enhanced">
          <section class="ics-ops-hero">
            <div class="ics-ops-hero__header">
              <div>
                <h2>{t('registration.title')}</h2>
              </div>
            </div>
          </section>
          <section class="ics-ops-grid ics-ops-grid--one">
            <div class="ics-card ics-ops-panel">
              <div class="ics-analysis-loading">
                <Loader2 size={48} class="ics-spin" />
                <p>{t('analysis.analyzing')}</p>
              </div>
            </div>
          </section>
        </div>
      );
    }

    return (
      <div class="ics-dashboard ics-dashboard--enhanced">
        <section class="ics-ops-hero">
          <div class="ics-ops-hero__header">
            <div>
              <h2>{t('registration.title')}</h2>
            </div>
            <div class="ics-ops-hero__controls">
              <button class="ics-ops-btn ics-ops-btn--ghost" onClick={handleBackToList}>
                <ArrowLeft size={14} />
                <span>{t('analysis.backToList')}</span>
              </button>
            </div>
          </div>
        </section>
        <section class="ics-ops-grid ics-ops-grid--one">
          <div class="ics-card ics-ops-panel">
            <div class="ics-card-body">
              <div class="ics-empty-text">{t('registration.noAnalysis')}</div>
            </div>
          </div>
        </section>
        <section class="ics-ops-grid ics-ops-grid--one">
          <div class="ics-registration-error">
            <AlertCircle size={16} />
            <span>{error}</span>
          </div>
        </section>
      </div>
    );
  }

  if (!currentAnalysisResult) {
    return (
      <div class="ics-dashboard ics-dashboard--enhanced">
        <section class="ics-ops-hero">
          <div class="ics-ops-hero__header">
            <div>
              <h2>{t('registration.title')}</h2>
            </div>
            <div class="ics-ops-hero__controls">
              <button class="ics-ops-btn ics-ops-btn--ghost" onClick={handleBackToList}>
                <ArrowLeft size={14} />
                <span>{t('analysis.backToList')}</span>
              </button>
            </div>
          </div>
        </section>
        <section class="ics-ops-grid ics-ops-grid--one">
          <div class="ics-card ics-ops-panel">
            <div class="ics-card-body">
              <div class="ics-empty-text">{t('registration.noAnalysis')}</div>
            </div>
          </div>
        </section>
      </div>
    );
  }

  const { classification } = currentAnalysisResult;
  const lineColumns = collectLineColumns(currentAnalysisResult, lineRows);
  const canAddLineRow = lineColumns.some(column => !isAutoGeneratedLineColumn(column));

  const handleAddLineRow = () => {
    if (!canAddLineRow) return;
    setLineRows(prev => [...prev, createEmptyLineRow(lineColumns)]);
  };

  const handleDeleteLineRow = (rowIndex: number) => {
    setLineRows(prev => prev.filter((_, index) => index !== rowIndex));
  };

  if (registrationResult?.success) {
    return (
      <div class="ics-dashboard ics-dashboard--enhanced">
        <section class="ics-ops-hero">
          <div class="ics-ops-hero__header">
            <div>
              <h2>
                <Database size={20} class="oj-sm-margin-2x-end" />
                {t('registration.title')}
              </h2>
            </div>
          </div>
        </section>
        <section class="ics-ops-grid ics-ops-grid--one">
          <div class="ics-card ics-ops-panel">
            <div class="ics-card-body">
              <div class="ics-registration-success">
                <CheckCircle2 size={48} class="ics-registration-success__icon" />
                <h3>{t('registration.success')}</h3>
                <p>{registrationResult.message}</p>
                <div class="ics-registration-success__details">
                  <span>Registration ID: {registrationResult.registration_id}</span>
                </div>
                <button
                  class="ics-ops-btn ics-ops-btn--primary"
                  onClick={handleBackToList}
                >
                  <ArrowLeft size={14} />
                  <span>{t('analysis.backToList')}</span>
                </button>
              </div>
            </div>
          </div>
        </section>
      </div>
    );
  }

  return (
    <div class="ics-dashboard ics-dashboard--enhanced">
      <section class="ics-ops-hero">
        <div class="ics-ops-hero__header">
          <div>
            <h2>
              <Database size={20} class="oj-sm-margin-2x-end" />
              {t('registration.title')}
            </h2>
            <p class="ics-ops-hero__subtitle">{t('registration.subtitle')}</p>
          </div>
          <div class="ics-ops-hero__controls">
            <button class="ics-ops-btn ics-ops-btn--ghost" onClick={handleBackToList}>
              <ArrowLeft size={14} />
              <span>{t('analysis.backToList')}</span>
            </button>
          </div>
        </div>
        <div class="ics-ops-hero__meta">
          <span>{currentAnalysisResult.file_name}</span>
        </div>
      </section>

      <section class="ics-ops-kpiGrid">
        <article class="ics-ops-kpiCard">
          <div class="ics-ops-kpiCard__label">
            <FileText size={14} />
            {t('analysis.classification.category')}
          </div>
          <div class="ics-ops-kpiCard__value">{classification.category}</div>
        </article>

        <article class="ics-ops-kpiCard">
          <div class="ics-ops-kpiCard__label">
            <Sparkles size={14} />
            {t('analysis.classification.confidence')}
          </div>
          <div class="ics-ops-kpiCard__value">{Math.round(classification.confidence * 100)}%</div>
        </article>

        <article class="ics-ops-kpiCard">
          <div class="ics-ops-kpiCard__label">
            <Table2 size={14} />
            {t('registration.fieldCount')}
          </div>
          <div class="ics-ops-kpiCard__value">
            {headerFields.length}H / {lineRows.length}L
          </div>
          <div class="ics-ops-kpiCard__meta">
            {t('registration.lineCount', { count: lineRows.length })}
          </div>
        </article>
      </section>

      <section class="ics-ops-grid ics-ops-grid--one">
        <div class="ics-card ics-ops-panel">
          <div class="ics-card-header oj-flex oj-sm-align-items-center">
            <Database size={18} class="oj-sm-margin-2x-end" />
            <span class="oj-typography-heading-xs">{t('registration.tableNames')}</span>
          </div>
          <div class="ics-card-body">
            <div class="ics-table-name-grid">
              <div class="ics-table-name-field">
                <label class="ics-table-name-field__label">{t('registration.tableName.header')}</label>
                <input type="text" class="ics-table-name-input" value={headerTableName} disabled />
              </div>
              <div class="ics-table-name-field">
                <label class="ics-table-name-field__label">{t('registration.tableName.line')}</label>
                <input type="text" class="ics-table-name-input" value={lineTableName || '--'} disabled />
              </div>
            </div>
          </div>
        </div>
      </section>

      <section class="ics-ops-grid ics-ops-grid--one">
        <div class="ics-registration-reviewLayout">
          <div class="ics-category-image-panel">
            <DocumentPreviewWorkspace
              fileIds={[currentAnalysisResult.file_id]}
              title={t('category.designer.reviewWorkspace')}
              hint={t('category.designer.reviewHint')}
            />
          </div>

          <div class="ics-card ics-ops-panel">
            <div class="ics-card-header">
              <span class="oj-typography-heading-xs">{t('registration.preview.title')}</span>
            </div>
            <div class="ics-card-body">
              <div class="ics-tabs" style={{ marginBottom: '8px' }}>
                <button
                  type="button"
                  class={`ics-tab ${activeTab === 'header' ? 'ics-tab--active' : ''}`}
                  onClick={() => setActiveTab('header')}
                >
                  <FileText size={14} />
                  {t('registration.tabHeader')}
                </button>
                <button
                  type="button"
                  class={`ics-tab ${activeTab === 'line' ? 'ics-tab--active' : ''}`}
                  onClick={() => setActiveTab('line')}
                >
                  <Table2 size={14} />
                  {t('registration.tabLine')}
                </button>
              </div>

              {activeTab === 'header' && (
                <div style={{ overflowX: 'auto' }}>
                  <table class="ics-table ics-table--compact">
                    <thead>
                      <tr>
                        <th>{t('registration.col.no')}</th>
                        <th>{t('registration.col.fieldName')}</th>
                        <th>{t('registration.col.fieldNameEn')}</th>
                        <th>{t('registration.col.dataType')}</th>
                        <th>{t('registration.col.value')}</th>
                      </tr>
                    </thead>
                    <tbody>
                      {headerFields.map((field, i) => {
                        const readOnly = isAutoGeneratedHeaderField(field);
                        return (
                          <tr key={i}>
                            <td>{i + 1}</td>
                            <td>{field.field_name}</td>
                            <td>{field.field_name_en || field.field_name}</td>
                            <td>{field.data_type}</td>
                            <td>
                              <input
                                type="text"
                                class={`ics-table-edit-input ${readOnly ? 'ics-table-edit-input--readonly' : ''}`}
                                value={String(field.value ?? '')}
                                readOnly={readOnly}
                                title={readOnly ? t('registration.autoGenerated') : undefined}
                                onInput={readOnly ? undefined : (e: Event) => updateHeaderFieldValue(i, (e.target as HTMLInputElement).value)}
                              />
                            </td>
                          </tr>
                        );
                      })}
                    </tbody>
                  </table>
                </div>
              )}

              {activeTab === 'line' && (
                <>
                  <div class="ics-registration-lineToolbar">
                    <button
                      type="button"
                      class="ics-ops-btn ics-ops-btn--ghost"
                      onClick={handleAddLineRow}
                      disabled={!canAddLineRow || isRegistering}
                    >
                      <Plus size={14} />
                      <span>{t('registration.action.addRow')}</span>
                    </button>
                  </div>

                  {lineRows.length > 0 ? (
                    <div style={{ overflowX: 'auto' }}>
                      <table class="ics-table ics-table--compact">
                        <thead>
                          <tr>
                            <th>{t('registration.col.rowNo')}</th>
                            <th class="ics-registration-rowActionCell">{t('registration.col.actions')}</th>
                            {lineColumns.map(col => (
                              <th key={col}>{col}</th>
                            ))}
                          </tr>
                        </thead>
                        <tbody>
                          {lineRows.map((row, rowIndex) => (
                            <tr key={rowIndex}>
                              <td>{rowIndex + 1}</td>
                              <td class="ics-registration-rowActionCell">
                                <button
                                  type="button"
                                  class="ics-ops-btn ics-ops-btn--ghost ics-ops-btn--danger ics-registration-rowActionBtn"
                                  onClick={() => handleDeleteLineRow(rowIndex)}
                                  disabled={isRegistering}
                                  title={t('registration.action.deleteRow')}
                                  aria-label={t('registration.action.deleteRow')}
                                >
                                  <Trash2 size={14} />
                                </button>
                              </td>
                              {lineColumns.map(col => {
                                const readOnly = isAutoGeneratedLineColumn(col);
                                return (
                                  <td key={`${rowIndex}-${col}`}>
                                    <input
                                      type="text"
                                      class={`ics-table-edit-input ${readOnly ? 'ics-table-edit-input--readonly' : ''}`}
                                      value={String(row[col] ?? '')}
                                      readOnly={readOnly}
                                      title={readOnly ? t('registration.autoGenerated') : undefined}
                                      onInput={readOnly ? undefined : (e: Event) => updateLineCell(rowIndex, col, (e.target as HTMLInputElement).value)}
                                    />
                                  </td>
                                );
                              })}
                            </tr>
                          ))}
                        </tbody>
                      </table>
                    </div>
                  ) : (
                    <div class="ics-empty-text">{t('registration.preview.noLineData')}</div>
                  )}
                </>
              )}
            </div>
          </div>
        </div>
      </section>

      <section class="ics-ops-grid ics-ops-grid--one">
        <div class="ics-registration-confirm">
          <label class="ics-table-mode-option">
            <input
              type="checkbox"
              checked={isConfirmed}
              onChange={(e) => setIsConfirmed((e.target as HTMLInputElement).checked)}
            />
            <span>{t('registration.confirm')}</span>
          </label>
        </div>
      </section>

      {(validationError || error) && (
        <section class="ics-ops-grid ics-ops-grid--one">
          <div class="ics-registration-error">
            <AlertCircle size={16} />
            <span>{validationError || error}</span>
          </div>
        </section>
      )}

      <section class="ics-ops-grid ics-ops-grid--one">
        <div class="ics-registration-actions">
          <button
            class="ics-ops-btn ics-ops-btn--ghost"
            onClick={handleBackToList}
            disabled={isRegistering}
          >
            <ArrowLeft size={14} />
            <span>{t('analysis.backToList')}</span>
          </button>
          <button
            class="ics-ops-btn ics-ops-btn--primary"
            onClick={handleRegister}
            disabled={isRegistering}
          >
            {isRegistering ? (
              <>
                <Loader2 size={14} class="ics-spin" />
                <span>{t('registration.executing')}</span>
              </>
            ) : (
              <>
                <Database size={14} />
                <span>{t('registration.execute')}</span>
              </>
            )}
          </button>
        </div>
      </section>
    </div>
  );
}
