/**
 * RegistrationView - DB登録確認画面 (SCR-004)
 * INSERTデータ確認・登録
 */
import type { JSX } from 'preact';
import { useState, useCallback, useEffect, useMemo } from 'preact/hooks';
import { useAppDispatch, useAppSelector } from '../../redux/store';
import {
  registerFile,
  clearRegistrationResult,
  clearAnalysisResult,
  fetchAnalysisResult,
  clearError
} from '../../redux/slices/denpyoSlice';
import { addNotification } from '../../redux/slices/notificationsSlice';
import { useLocation, useNavigate } from 'react-router-dom';
import { APP_ROUTES } from '../../constants/routes';
import { t } from '../../i18n';
import type { AnalysisResult, ExtractedField, RegistrationRequest } from '../../types/denpyoTypes';
import {
  ArrowLeft,
  Database,
  FileText,
  Table2,
  Loader2,
  AlertCircle,
  Plus,
  Trash2
} from 'lucide-react';
import { DocumentPreviewWorkspace } from '../../components/DocumentPreviewWorkspace';
import { buildSyncedPanelMaxHeightStyle, useObservedElementHeight } from '../../hooks/useObservedElementHeight';

const AUTO_GENERATED_HEADER_COLUMNS = new Set(['HEADER_ID']);
const AUTO_GENERATED_LINE_COLUMNS = ['HEADER_ID', 'LINE_ID'];
const SUCCESS_REDIRECT_DELAY_MS = 1200;

function normalizeColumnName(value: string | null | undefined): string {
  return String(value ?? '').trim().toUpperCase();
}

function isAutoGeneratedHeaderField(field: ExtractedField): boolean {
  return AUTO_GENERATED_HEADER_COLUMNS.has(normalizeColumnName(field.field_name_en || field.field_name));
}

function isAutoGeneratedLineColumn(columnName: string): boolean {
  return AUTO_GENERATED_LINE_COLUMNS.includes(normalizeColumnName(columnName));
}

function collectLineColumns(analysisResult: AnalysisResult, lineRows: Record<string, string>[]): string[] {
  const orderedColumns: string[] = [];
  const seenColumns = new Set<string>();

  const pushColumn = (columnName: string | null | undefined) => {
    const label = String(columnName ?? '').trim();
    if (!label) return;

    const normalizedName = normalizeColumnName(label);
    if (seenColumns.has(normalizedName)) return;

    seenColumns.add(normalizedName);
    orderedColumns.push(label);
  };

  analysisResult.table_schema?.line_columns?.forEach(column => pushColumn(column.column_name));
  analysisResult.extraction.line_fields?.forEach(field => pushColumn(field.field_name_en || field.field_name));
  lineRows.forEach(row => Object.keys(row || {}).forEach(pushColumn));

  const regularColumns: string[] = [];
  const systemColumns: string[] = [];
  orderedColumns.forEach(column => {
    if (isAutoGeneratedLineColumn(column)) {
      systemColumns.push(column);
      return;
    }
    regularColumns.push(column);
  });

  systemColumns.sort((a, b) => {
    return AUTO_GENERATED_LINE_COLUMNS.indexOf(normalizeColumnName(a)) - AUTO_GENERATED_LINE_COLUMNS.indexOf(normalizeColumnName(b));
  });

  return [...regularColumns, ...systemColumns];
}

function createEmptyLineRow(columns: string[]): Record<string, string> {
  const row: Record<string, string> = {};
  columns.forEach(column => {
    row[column] = '';
  });
  return row;
}

export function RegistrationView() {
  const dispatch = useAppDispatch();
  const analysisResult = useAppSelector(state => state.denpyo.analysisResult);
  const isRegistering = useAppSelector(state => state.denpyo.isRegistering);
  const registrationResult = useAppSelector(state => state.denpyo.registrationResult);
  const isAnalyzing = useAppSelector(state => state.denpyo.isAnalyzing);
  const error = useAppSelector(state => state.denpyo.error);
  const navigate = useNavigate();
  const location = useLocation();
  const fileId = new URLSearchParams(location.search).get('fileId');
  const currentAnalysisResult = analysisResult && (!fileId || String(analysisResult.file_id) === String(fileId))
    ? analysisResult
    : null;

  const [headerTableName, setHeaderTableName] = useState('');
  const [lineTableName, setLineTableName] = useState('');
  const [headerFields, setHeaderFields] = useState<ExtractedField[]>([]);
  const [lineRows, setLineRows] = useState<Record<string, string>[]>([]);
  const [isConfirmed, setIsConfirmed] = useState(false);
  const [validationError, setValidationError] = useState('');
  const [activeTab, setActiveTab] = useState<'header' | 'line'>('header');
  const [isRedirectingAfterSuccess, setIsRedirectingAfterSuccess] = useState(false);
  const [isReviewCollapsed, setIsReviewCollapsed] = useState(false);
  const isReviewHeightSyncEnabled = !isReviewCollapsed;
  const { elementRef: reviewPanelRef, height: reviewPanelHeight } = useObservedElementHeight<HTMLDivElement>(isReviewHeightSyncEnabled);
  const syncedPreviewStyle = buildSyncedPanelMaxHeightStyle(reviewPanelHeight);

  useEffect(() => {
    dispatch(clearRegistrationResult());
    dispatch(clearError());
  }, [dispatch, fileId]);

  useEffect(() => {
    if (!fileId || currentAnalysisResult) return;
    dispatch(fetchAnalysisResult(fileId));
  }, [currentAnalysisResult, dispatch, fileId]);

  useEffect(() => {
    if (!registrationResult?.success) {
      setIsRedirectingAfterSuccess(false);
      return;
    }

    setIsRedirectingAfterSuccess(true);
    dispatch(addNotification({
      type: 'success',
      message: registrationResult.message,
      autoClose: true,
    }));

    const timerId = window.setTimeout(() => {
      dispatch(clearRegistrationResult());
      dispatch(clearAnalysisResult());
      dispatch(clearError());
      navigate(APP_ROUTES.fileList);
    }, SUCCESS_REDIRECT_DELAY_MS);

    return () => window.clearTimeout(timerId);
  }, [dispatch, navigate, registrationResult]);

  useEffect(() => {
    if (!currentAnalysisResult) return;

    const ddl = currentAnalysisResult.ddl_suggestion;
    setHeaderTableName(ddl.header_table_name || '');
    setLineTableName(ddl.line_table_name || '');
    setHeaderFields(currentAnalysisResult.extraction.header_fields || []);

    const extractedLines = (currentAnalysisResult.extraction.raw_lines || []).map(row => {
      const normalized: Record<string, string> = {};
      Object.entries(row || {}).forEach(([key, value]) => {
        normalized[key] = String(value ?? '');
      });
      return normalized;
    });

    if (extractedLines.length > 0) {
      setLineRows(extractedLines);
    } else {
      const fallbackLine: Record<string, string> = {};
      (currentAnalysisResult.extraction.line_fields || []).forEach(field => {
        const key = field.field_name_en || field.field_name;
        if (key) fallbackLine[key] = String(field.value ?? '');
      });
      setLineRows(Object.keys(fallbackLine).length > 0 ? [fallbackLine] : []);
    }

    setActiveTab('header');
    setIsConfirmed(false);
    setValidationError('');
  }, [currentAnalysisResult]);

  const handleBackToList = useCallback(() => {
    dispatch(clearRegistrationResult());
    dispatch(clearAnalysisResult());
    dispatch(clearError());
    navigate(APP_ROUTES.fileList);
  }, [dispatch, navigate]);

  const updateHeaderFieldValue = (index: number, value: string) => {
    setHeaderFields(prev => prev.map((f, idx) => (idx === index ? { ...f, value } : f)));
  };

  const updateLineCell = (rowIndex: number, col: string, value: string) => {
    setLineRows(prev => prev.map((row, idx) => (idx === rowIndex ? { ...row, [col]: value } : row)));
  };

  const handleRegister = useCallback(async () => {
    if (!currentAnalysisResult) return;
    if (registrationResult?.success || isRedirectingAfterSuccess) return;

    if (!isConfirmed) {
      setValidationError(t('registration.error.notConfirmed'));
      return;
    }
    if (!headerTableName.trim()) {
      setValidationError(t('registration.error.noHeaderTable'));
      return;
    }
    setValidationError('');

    const normalizedLineRows = lineRows
      .map(row => {
        const normalized: Record<string, string> = {};
        Object.entries(row).forEach(([key, value]) => {
          if (isAutoGeneratedLineColumn(key)) return;

          const textValue = String(value ?? '');
          if (!textValue.trim()) return;

          normalized[key] = textValue;
        });
        return normalized;
      })
      .filter(row => Object.keys(row).length > 0);

    const data: RegistrationRequest = {
      category_id: currentAnalysisResult.category_id,
      category_name: currentAnalysisResult.classification.category,
      category_name_en: currentAnalysisResult.ddl_suggestion.table_prefix || '',
      header_table_name: headerTableName.trim(),
      line_table_name: lineTableName.trim(),
      header_ddl: currentAnalysisResult.ddl_suggestion.header_ddl || '',
      line_ddl: currentAnalysisResult.ddl_suggestion.line_ddl || '',
      ai_confidence: currentAnalysisResult.classification.confidence,
      line_count: normalizedLineRows.length,
      header_fields: headerFields,
      raw_lines: normalizedLineRows,
    };

    dispatch(registerFile({ fileId: currentAnalysisResult.file_id, data }));
  }, [
    dispatch,
    currentAnalysisResult,
    headerTableName,
    lineTableName,
    headerFields,
    lineRows,
    isConfirmed,
    registrationResult,
    isRedirectingAfterSuccess,
  ]);

  if (fileId && !currentAnalysisResult) {
    if (isAnalyzing || !error) {
      return (
        <div class="ics-dashboard ics-dashboard--enhanced">
          <section class="ics-ops-hero">
            <div class="ics-ops-hero__header">
              <div>
                <h2>{t('registration.title')}</h2>
              </div>
            </div>
          </section>
          <section class="ics-ops-grid ics-ops-grid--one">
            <div class="ics-card ics-ops-panel">
              <div class="ics-analysis-loading">
                <Loader2 size={48} class="ics-spin" />
                <p>{t('analysis.analyzing')}</p>
              </div>
            </div>
          </section>
        </div>
      );
    }

    return (
      <div class="ics-dashboard ics-dashboard--enhanced">
        <section class="ics-ops-hero">
          <div class="ics-ops-hero__header">
            <div>
              <h2>{t('registration.title')}</h2>
            </div>
            <div class="ics-ops-hero__controls">
              <button class="ics-ops-btn ics-ops-btn--ghost" onClick={handleBackToList}>
                <ArrowLeft size={14} />
                <span>{t('analysis.backToList')}</span>
              </button>
            </div>
          </div>
        </section>
        <section class="ics-ops-grid ics-ops-grid--one">
          <div class="ics-card ics-ops-panel">
            <div class="ics-card-body">
              <div class="ics-empty-text">{t('registration.noAnalysis')}</div>
            </div>
          </div>
        </section>
        <section class="ics-ops-grid ics-ops-grid--one">
          <div class="ics-registration-error">
            <AlertCircle size={16} />
            <span>{error}</span>
          </div>
        </section>
      </div>
    );
  }

  if (!currentAnalysisResult) {
    return (
      <div class="ics-dashboard ics-dashboard--enhanced">
        <section class="ics-ops-hero">
          <div class="ics-ops-hero__header">
            <div>
              <h2>{t('registration.title')}</h2>
            </div>
            <div class="ics-ops-hero__controls">
              <button class="ics-ops-btn ics-ops-btn--ghost" onClick={handleBackToList}>
                <ArrowLeft size={14} />
                <span>{t('analysis.backToList')}</span>
              </button>
            </div>
          </div>
        </section>
        <section class="ics-ops-grid ics-ops-grid--one">
          <div class="ics-card ics-ops-panel">
            <div class="ics-card-body">
              <div class="ics-empty-text">{t('registration.noAnalysis')}</div>
            </div>
          </div>
        </section>
      </div>
    );
  }

  const visibleHeaderFields = headerFields
    .map((field, index) => ({ field, index }))
    .filter(({ field }) => !isAutoGeneratedHeaderField(field));
  const lineColumns = collectLineColumns(currentAnalysisResult, lineRows);
  const visibleLineColumns = lineColumns.filter(column => !isAutoGeneratedLineColumn(column));
  const canAddLineRow = visibleLineColumns.length > 0;

  const lineColWidths = useMemo(() => {
    const CH_PX = 10;
    const PADDING = 24;
    const widths: Record<string, number> = {};
    for (const col of visibleLineColumns) {
      const headerLen = col.length;
      const maxDataLen = lineRows.reduce((max, row) => Math.max(max, String(row[col] ?? '').length), 0);
      widths[col] = Math.max(headerLen, maxDataLen) * CH_PX + PADDING;
    }
    return widths;
  }, [visibleLineColumns, lineRows]);

  const handleAddLineRow = () => {
    if (!canAddLineRow) return;
    setLineRows(prev => [...prev, createEmptyLineRow(visibleLineColumns)]);
  };

  const handleDeleteLineRow = (rowIndex: number) => {
    setLineRows(prev => prev.filter((_, index) => index !== rowIndex));
  };

  return (
    <div class="ics-dashboard ics-dashboard--enhanced">
      <section class="ics-ops-hero">
        <div class="ics-ops-hero__header">
          <div>
            <h2>
              <Database size={20} class="oj-sm-margin-2x-end" />
              {t('registration.title')}
            </h2>
            <p class="ics-ops-hero__subtitle">{t('registration.subtitle')}</p>
          </div>
          <div class="ics-ops-hero__controls">
            <button class="ics-ops-btn ics-ops-btn--ghost" onClick={handleBackToList}>
              <ArrowLeft size={14} />
              <span>{t('analysis.backToList')}</span>
            </button>
          </div>
        </div>
      </section>

      <section class="ics-ops-grid ics-ops-grid--one">
        <div
          class={`ics-registration-reviewLayout ${isReviewCollapsed ? 'is-review-collapsed' : ''}`}
          style={{ gridTemplateColumns: isReviewCollapsed ? '108px minmax(0, 1fr)' : 'minmax(420px, 1.02fr) minmax(560px, 1.18fr)' }}
        >
          <div
            ref={reviewPanelRef}
            class={`ics-category-image-panel ${isReviewCollapsed ? 'is-collapsed' : ''}`}
          >
            <DocumentPreviewWorkspace
              fileIds={[currentAnalysisResult.file_id]}
              title={t('category.designer.reviewWorkspace')}
              hint={t('category.designer.reviewHint')}
              collapsible
              isCollapsed={isReviewCollapsed}
              onToggleCollapsed={setIsReviewCollapsed}
            />
          </div>

          <div class="ics-card ics-ops-panel ics-registration-reviewCard ics-synced-panel-height" style={syncedPreviewStyle}>
            <div class="ics-card-header">
              <span class="oj-typography-heading-xs">{t('registration.preview.title')}</span>
            </div>
            <div class="ics-card-body ics-registration-reviewCard__body">
              <div class="ics-registration-reviewCard__scroll ics-synced-panel-scroll">
                <div class="ics-tabs" style={{ marginBottom: '8px' }}>
                  <button
                    type="button"
                    class={`ics-tab ${activeTab === 'header' ? 'ics-tab--active' : ''}`}
                    onClick={() => setActiveTab('header')}
                  >
                    <FileText size={14} />
                    {t('registration.tabHeader')}
                  </button>
                  <button
                    type="button"
                    class={`ics-tab ${activeTab === 'line' ? 'ics-tab--active' : ''}`}
                    onClick={() => setActiveTab('line')}
                  >
                    <Table2 size={14} />
                    {t('registration.tabLine')}
                  </button>
                </div>

                {activeTab === 'header' && (
                  <div style={{ overflowX: 'auto' }}>
                    <table class="ics-table ics-table--compact">
                      <thead>
                        <tr>
                          <th class="ics-table__index-col">{t('registration.col.no')}</th>
                          <th>{t('registration.col.fieldName')}</th>
                          <th>{t('registration.col.fieldNameEn')}</th>
                          <th>{t('registration.col.dataType')}</th>
                          <th>{t('registration.col.value')}</th>
                        </tr>
                      </thead>
                      <tbody>
                        {visibleHeaderFields.map(({ field, index }, visibleIndex) => {
                          const readOnly = isAutoGeneratedHeaderField(field);
                          return (
                            <tr key={index}>
                              <td class="ics-table__index-col">{visibleIndex + 1}</td>
                              <td>{field.field_name}</td>
                              <td>{field.field_name_en || field.field_name}</td>
                              <td>{field.data_type}</td>
                              <td>
                                <input
                                  type="text"
                                  class={`ics-table-edit-input ${readOnly ? 'ics-table-edit-input--readonly' : ''}`}
                                  value={String(field.value ?? '')}
                                  readOnly={readOnly}
                                  title={readOnly ? t('registration.autoGenerated') : undefined}
                                  onInput={readOnly ? undefined : (e: Event) => updateHeaderFieldValue(index, (e.target as HTMLInputElement).value)}
                                />
                              </td>
                            </tr>
                          );
                        })}
                      </tbody>
                    </table>
                  </div>
                )}

                {activeTab === 'line' && (
                  <>
                    {lineRows.length > 0 ? (
                      <div style={{ overflowX: 'auto' }}>
                        <table class="ics-table ics-table--compact">
                          <thead>
                            <tr>
                              <th class="ics-table__index-col">{t('registration.col.no')}</th>
                              {visibleLineColumns.map(col => (
                                <th key={col} style={{ width: `${lineColWidths[col]}px`, minWidth: `${lineColWidths[col]}px` }}>{col}</th>
                              ))}
                              <th class="ics-registration-rowActionCell">{t('registration.col.actions')}</th>
                            </tr>
                          </thead>
                          <tbody>
                            {lineRows.map((row, rowIndex) => (
                              <tr key={rowIndex}>
                                <td class="ics-table__index-col">{rowIndex + 1}</td>
                                {visibleLineColumns.map(col => {
                                  const readOnly = isAutoGeneratedLineColumn(col);
                                  return (
                                    <td key={`${rowIndex}-${col}`} style={{ width: `${lineColWidths[col]}px`, minWidth: `${lineColWidths[col]}px` }}>
                                      <input
                                        type="text"
                                        class={`ics-table-edit-input ${readOnly ? 'ics-table-edit-input--readonly' : ''}`}
                                        value={String(row[col] ?? '')}
                                        readOnly={readOnly}
                                        title={readOnly ? t('registration.autoGenerated') : undefined}
                                        onInput={readOnly ? undefined : (e: Event) => updateLineCell(rowIndex, col, (e.target as HTMLInputElement).value)}
                                      />
                                    </td>
                                  );
                                })}
                                <td class="ics-registration-rowActionCell">
                                  <button
                                    type="button"
                                    class="ics-ops-btn ics-ops-btn--ghost ics-ops-btn--danger ics-registration-rowActionBtn"
                                    onClick={() => handleDeleteLineRow(rowIndex)}
                                    disabled={isRegistering}
                                    title={t('registration.action.deleteRow')}
                                    aria-label={t('registration.action.deleteRow')}
                                  >
                                    <Trash2 size={14} />
                                  </button>
                                </td>
                              </tr>
                            ))}
                          </tbody>
                        </table>
                      </div>
                    ) : (
                      <div class="ics-empty-text">{t('registration.preview.noLineData')}</div>
                    )}
                    <div class="ics-table-designer__actions">
                      <button
                        type="button"
                        class="ics-ops-btn ics-ops-btn--ghost"
                        onClick={handleAddLineRow}
                        disabled={!canAddLineRow || isRegistering}
                      >
                        <Plus size={14} />
                        <span>{t('registration.action.addRow')}</span>
                      </button>
                    </div>
                  </>
                )}
              </div>
            </div>
          </div>
        </div>
      </section>

      <section class="ics-ops-grid ics-ops-grid--one">
        <div class="ics-registration-confirm">
          <label class="ics-table-mode-option">
            <input
              type="checkbox"
              checked={isConfirmed}
              onChange={(e) => setIsConfirmed((e.target as HTMLInputElement).checked)}
            />
            <span>{t('registration.confirm')}</span>
          </label>
        </div>
      </section>

      {(validationError || error) && (
        <section class="ics-ops-grid ics-ops-grid--one">
          <div class="ics-registration-error">
            <AlertCircle size={16} />
            <span>{validationError || error}</span>
          </div>
        </section>
      )}

      <section class="ics-ops-grid ics-ops-grid--one">
        <div class="ics-registration-actions">
          <button
            class="ics-ops-btn ics-ops-btn--ghost"
            onClick={handleBackToList}
            disabled={isRegistering || isRedirectingAfterSuccess}
          >
            <ArrowLeft size={14} />
            <span>{t('analysis.backToList')}</span>
          </button>
          <button
            class="ics-ops-btn ics-ops-btn--primary"
            onClick={handleRegister}
            disabled={isRegistering || isRedirectingAfterSuccess}
          >
            {isRegistering || isRedirectingAfterSuccess ? (
              <>
                <Loader2 size={14} class="ics-spin" />
                <span>{isRedirectingAfterSuccess ? t('registration.success') : t('registration.executing')}</span>
              </>
            ) : (
              <>
                <Database size={14} />
                <span>{t('registration.execute')}</span>
              </>
            )}
          </button>
        </div>
      </section>
    </div>
  );
}
